# Generated by Django 3.2.19 on 2023-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagesdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(blank=True, db_column='Customerid', max_length=255, null=True)),
                ('customernmae', models.CharField(blank=True, db_column='CustomerNmae', max_length=100, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=1500, null=True)),
                ('sendingtime', models.DateTimeField(blank=True, db_column='sendingTime', null=True)),
            ],
            options={
                'db_table': 'messagesdetails',
                'managed': False,
            },
        ),
    ]
